// <auto-generated />
using DnDEncounterGenerator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDEncounterGenerator.Api.Migrations
{
    [DbContext(typeof(MonsterDataContext))]
    partial class MonsterDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DnDEncounterGenerator.Shared.Encounter", b =>
                {
                    b.Property<int>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EncounterId");

                    b.ToTable("Encounter", (string)null);

                    b.HasData(
                        new
                        {
                            EncounterId = 1,
                            Description = "This is an encounter with some goblins.",
                            Name = "There Be Goblins"
                        },
                        new
                        {
                            EncounterId = 2,
                            Description = "This is an encounter with some orcs.",
                            Name = "Big Ol Orcs"
                        },
                        new
                        {
                            EncounterId = 3,
                            Description = "This is an encounter with some kobolds.",
                            Name = "Fearsom Kobolds"
                        });
                });

            modelBuilder.Entity("DnDEncounterGenerator.Shared.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ChallengeRating")
                        .HasColumnType("REAL");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("MonsterId");

                    b.ToTable("Monster", (string)null);

                    b.HasData(
                        new
                        {
                            MonsterId = 1,
                            ArmorClass = 10,
                            ChallengeRating = 1.0,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 20,
                            Intelligence = 10,
                            Name = "Goblin",
                            Speed = 30,
                            Strength = 10,
                            Wisdom = 10
                        },
                        new
                        {
                            MonsterId = 2,
                            ArmorClass = 10,
                            ChallengeRating = 1.0,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 20,
                            Intelligence = 10,
                            Name = "Orc",
                            Speed = 30,
                            Strength = 10,
                            Wisdom = 10
                        },
                        new
                        {
                            MonsterId = 3,
                            ArmorClass = 10,
                            ChallengeRating = 1.0,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 20,
                            Intelligence = 10,
                            Name = "Kobold",
                            Speed = 30,
                            Strength = 10,
                            Wisdom = 10
                        });
                });

            modelBuilder.Entity("EncounterMonster", b =>
                {
                    b.Property<int>("EncountersEncounterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonstersMonsterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EncountersEncounterId", "MonstersMonsterId");

                    b.HasIndex("MonstersMonsterId");

                    b.ToTable("EncounterMonster");
                });

            modelBuilder.Entity("EncounterMonster", b =>
                {
                    b.HasOne("DnDEncounterGenerator.Shared.Encounter", null)
                        .WithMany()
                        .HasForeignKey("EncountersEncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DnDEncounterGenerator.Shared.Monster", null)
                        .WithMany()
                        .HasForeignKey("MonstersMonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
