// <auto-generated />
using DnDEncounterGenerator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDEncounterGenerator.Api.Migrations
{
    [DbContext(typeof(MonsterDataContext))]
    partial class MonsterDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("DnDEncounterGenerator.Shared.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ChallengeRating")
                        .HasColumnType("REAL");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("MonsterId");

                    b.ToTable("Monster", (string)null);

                    b.HasData(
                        new
                        {
                            MonsterId = 1,
                            ArmorClass = 10,
                            ChallengeRating = 1.0,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 20,
                            Intelligence = 10,
                            Name = "Goblin",
                            Speed = 30,
                            Strength = 10,
                            Wisdom = 10
                        },
                        new
                        {
                            MonsterId = 2,
                            ArmorClass = 10,
                            ChallengeRating = 1.0,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 20,
                            Intelligence = 10,
                            Name = "Orc",
                            Speed = 30,
                            Strength = 10,
                            Wisdom = 10
                        },
                        new
                        {
                            MonsterId = 3,
                            ArmorClass = 10,
                            ChallengeRating = 1.0,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 20,
                            Intelligence = 10,
                            Name = "Kobold",
                            Speed = 30,
                            Strength = 10,
                            Wisdom = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
