// <auto-generated />
using DnDEncounterGenerator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDEncounterGenerator.Migrations
{
    [DbContext(typeof(MonsterContext))]
    [Migration("20250225185525_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DnDEncounterGenerator.Data.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("MonsterId");

                    b.ToTable("Monsters", (string)null);

                    b.HasData(
                        new
                        {
                            MonsterId = 1,
                            Health = 10,
                            Name = "Orc"
                        },
                        new
                        {
                            MonsterId = 2,
                            Health = 8,
                            Name = "Goblin"
                        },
                        new
                        {
                            MonsterId = 3,
                            Health = 6,
                            Name = "Kobold"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
