// <auto-generated />
using DnDEncounterGenerator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnDEncounterGenerator.Migrations
{
    [DbContext(typeof(MonsterContext))]
    [Migration("20250225203153_ExpandingTableContents")]
    partial class ExpandingTableContents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DnDEncounterGenerator.Data.Monster", b =>
                {
                    b.Property<int>("MonsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("MonsterId");

                    b.ToTable("Monsters", (string)null);

                    b.HasData(
                        new
                        {
                            MonsterId = 1,
                            ArmorClass = 10,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 10,
                            Intelligence = 10,
                            Name = "Orc",
                            Speed = "20 ft",
                            Strength = 10,
                            Wisdom = 10
                        },
                        new
                        {
                            MonsterId = 2,
                            ArmorClass = 10,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 10,
                            Intelligence = 10,
                            Name = "Goblin",
                            Speed = "20 ft",
                            Strength = 10,
                            Wisdom = 10
                        },
                        new
                        {
                            MonsterId = 3,
                            ArmorClass = 10,
                            Charisma = 10,
                            Constitution = 10,
                            Dexterity = 10,
                            HitPoints = 10,
                            Intelligence = 10,
                            Name = "Kobold",
                            Speed = "20 ft",
                            Strength = 10,
                            Wisdom = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
